# Generated by Django 4.2.16 on 2025-08-12 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("VIEW", "View"),
                            ("PERMISSION_CHANGE", "Permission Change"),
                            ("SYSTEM_CHANGE", "System Change"),
                            ("BANK_TRANSFER_CREATED", "Bank Transfer Created"),
                            ("BANK_TRANSFER_PROCESSED", "Bank Transfer Processed"),
                            ("BANK_TRANSFER_COMPLETED", "Bank Transfer Completed"),
                            ("BANK_TRANSFER_FAILED", "Bank Transfer Failed"),
                            ("BANK_TRANSFER_PENDING", "Bank Transfer Pending"),
                            ("BANK_TRANSFER_SENT", "Bank Transfer Sent"),
                            ("BANK_TRANSFER_GENERATED", "Bank Transfer Generated"),
                        ],
                        max_length=50,
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=100, null=True)),
                ("object_id", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="core_auditl_timesta_80074f_idx"
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="core_auditl_user_id_7b678c_idx",
                    ),
                    models.Index(
                        fields=["action"], name="core_auditl_action_d9fb24_idx"
                    ),
                ],
            },
        ),
    ]
