# Generated by Django 4.2.16 on 2025-09-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_create_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenseapprovalstep",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="expenseapprovalstep",
            name="name",
            field=models.CharField(default="Approval Step", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="expenseapprovalworkflow",
            name="total_steps",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
