# Generated by Django 4.2.16 on 2025-09-09 21:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(max_length=20)),
                ("date_registered", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "ordering": ["-date_registered"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("standard", "Standard"),
                            ("premium", "Premium"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("max_employees", models.IntegerField(default=50)),
                ("max_users", models.IntegerField(default=5)),
                ("price_monthly", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "price_quarterly",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "price_biannual",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("price_annual", models.DecimalField(decimal_places=2, max_digits=10)),
                ("features", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Subscription Tier",
                "verbose_name_plural": "Subscription Tiers",
                "ordering": ["price_monthly"],
                "indexes": [
                    models.Index(fields=["name"], name="License_sub_name_5e8c4f_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_key",
                    models.CharField(editable=False, max_length=100, unique=True),
                ),
                ("issue_date", models.DateField(auto_now_add=True)),
                ("start_date", models.DateField()),
                ("expiration_date", models.DateField()),
                (
                    "duration_months",
                    models.IntegerField(
                        choices=[
                            (1, "Monthly"),
                            (3, "3 Months"),
                            (6, "6 Months"),
                            (12, "1 Year"),
                        ]
                    ),
                ),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "hardware_fingerprint",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("last_verified", models.DateTimeField(blank=True, null=True)),
                ("last_online_check", models.DateTimeField(blank=True, null=True)),
                ("activation_count", models.IntegerField(default=0)),
                ("max_activations", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="license",
                        to="License.company",
                    ),
                ),
                (
                    "subscription_tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="licenses",
                        to="License.subscriptiontier",
                    ),
                ),
            ],
            options={
                "verbose_name": "License",
                "verbose_name_plural": "Licenses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["name"], name="License_com_name_ba4716_idx"),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["uuid"], name="License_com_uuid_c77d8a_idx"),
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(
                fields=["license_key"], name="License_lic_license_297591_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(
                fields=["expiration_date"], name="License_lic_expirat_db1f11_idx"
            ),
        ),
    ]
