# Generated by Django 4.2.16 on 2025-09-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("License", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="license",
            name="license_server_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="license",
            name="max_offline_days",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="license",
            name="online_check_required",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="license",
            name="remotely_revoked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="license",
            name="revocation_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
