# Generated by Django 4.2.16 on 2025-09-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "License",
            "0002_license_license_server_url_license_max_offline_days_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="license",
            name="was_revoked",
            field=models.BooleanField(default=False),
        ),
    ]
