# Generated by Django 4.2.16 on 2025-09-19 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("License", "0003_license_was_revoked"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptiontier",
            name="features",
        ),
    ]
