# Generated by Django 4.2.16 on 2025-09-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("License", "0004_remove_features_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="license",
            name="failed_verification_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="license",
            name="integrity_signature",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="license",
            name="last_failed_verification",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="LicenseAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.CharField(blank=True, max_length=255, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=False)),
                (
                    "license_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "attempt_type",
                    models.CharField(
                        choices=[
                            ("activation", "Activation"),
                            ("verification", "Verification"),
                            ("login", "Login"),
                            ("renewal", "Renewal"),
                            ("revocation", "Revocation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cpu_info", models.CharField(blank=True, max_length=255, null=True)),
                ("ram_info", models.CharField(blank=True, max_length=100, null=True)),
                ("disk_info", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "mac_address",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("os_info", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "hardware_fingerprint",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ip_address", "timestamp"],
                        name="License_lic_ip_addr_ecf8e8_idx",
                    ),
                    models.Index(
                        fields=["license_key", "timestamp"],
                        name="License_lic_license_79670a_idx",
                    ),
                    models.Index(
                        fields=["hardware_fingerprint"],
                        name="License_lic_hardwar_948146_idx",
                    ),
                ],
            },
        ),
    ]
