# Generated by Django 4.2.16 on 2025-09-16 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_importjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="is_excessive_lunch_break",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="attendance",
            name="is_other_staff_special_late",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="attendance",
            name="weekend_work_time",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name="monthlyattendancesummary",
            name="excessive_lunch_breaks",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="monthlyattendancesummary",
            name="other_staff_special_late_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="monthlyattendancesummary",
            name="weekend_work_hours",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("PRESENT", "Present"),
                    ("ABSENT", "Absent"),
                    ("LATE", "Late"),
                    ("HALF_DAY", "Half Day"),
                    ("LEAVE", "On Leave"),
                    ("HOLIDAY", "Holiday"),
                    ("INCOMPLETE", "Incomplete"),
                    ("EARLY_DEPARTURE", "Early Departure"),
                    ("FULL_DAY_DEDUCTION", "Full Day Deduction"),
                ],
                default="ABSENT",
                max_length=20,
            ),
        ),
    ]
