# Generated by Django 4.2.16 on 2025-08-12 20:13

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("attendance", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2020),
                            django.core.validators.MaxValueValidator(2050),
                        ]
                    ),
                ),
                (
                    "month",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("period_name", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("APPROVED", "Approved"),
                            ("PAID", "Paid"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("processing_date", models.DateField()),
                ("cutoff_date", models.DateField()),
                ("total_employees", models.PositiveIntegerField(default=0)),
                ("total_working_days", models.PositiveIntegerField(default=0)),
                (
                    "total_gross_salary",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_deductions",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_net_salary",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_epf_employee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_epf_employer",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_etf_contribution",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("role_based_summary", models.JSONField(blank=True, default=dict)),
                ("department_summary", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_payroll_periods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_payroll_periods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_periods",
                "ordering": ["-year", "-month"],
            },
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference_number", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("CALCULATED", "Calculated"),
                            ("APPROVED", "Approved"),
                            ("PAID", "Paid"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("sr_no", models.PositiveIntegerField(default=0)),
                ("working_days", models.PositiveIntegerField(default=0)),
                ("attended_days", models.PositiveIntegerField(default=0)),
                (
                    "basic_salary",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "ot_basic",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "bonus_1",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "bonus_2",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "transport_allowance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "telephone_allowance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "fuel_allowance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "meal_allowance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "attendance_bonus",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "performance_bonus",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "interim_allowance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "education_allowance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "religious_pay",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "friday_salary",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "friday_overtime",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "regular_overtime",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "friday_work_days",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("0.0"), max_digits=5
                    ),
                ),
                (
                    "friday_ot_hours",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("0.0"), max_digits=5
                    ),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "gross_salary",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("working_day_meals", models.PositiveIntegerField(default=0)),
                ("leave_days", models.PositiveIntegerField(default=0)),
                (
                    "leave_deduction",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "late_penalty",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "lunch_violation_penalty",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "advance_deduction",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "epf_salary_base",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "employee_epf_contribution",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "employer_epf_contribution",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "etf_contribution",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "income_tax",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_deductions",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "net_salary",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "fuel_per_day",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                (
                    "meal_per_day",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                (
                    "role_based_calculations",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_payslips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "calculated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calculated_payslips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "monthly_summary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payslips",
                        to="attendance.monthlyattendancesummary",
                    ),
                ),
                (
                    "payroll_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="payroll.payrollperiod",
                    ),
                ),
            ],
            options={
                "db_table": "payroll_payslips",
                "ordering": [
                    "-payroll_period__year",
                    "-payroll_period__month",
                    "employee__employee_code",
                ],
            },
        ),
        migrations.CreateModel(
            name="PayrollDepartmentSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("employee_count", models.PositiveIntegerField(default=0)),
                (
                    "total_basic_salary",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_allowances",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_overtime_pay",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_gross_salary",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_deductions",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_net_salary",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_epf_employee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_epf_employer",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_etf_contribution",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "average_salary",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "department_budget",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "budget_utilization_percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("role_breakdown", models.JSONField(blank=True, default=dict)),
                ("performance_metrics", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_summaries",
                        to="accounts.department",
                    ),
                ),
                (
                    "payroll_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_summaries",
                        to="payroll.payrollperiod",
                    ),
                ),
            ],
            options={
                "db_table": "payroll_department_summaries",
                "ordering": ["payroll_period", "department__name"],
            },
        ),
        migrations.CreateModel(
            name="PayrollBankTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("batch_reference", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("GENERATED", "Generated"),
                            ("SENT", "Sent to Bank"),
                            ("PROCESSED", "Processed by Bank"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("total_employees", models.PositiveIntegerField(default=0)),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("bank_file_path", models.CharField(blank=True, max_length=500)),
                ("bank_file_format", models.CharField(default="CSV", max_length=20)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("bank_response", models.JSONField(blank=True, default=dict)),
                ("error_details", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_bank_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payroll_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_transfers",
                        to="payroll.payrollperiod",
                    ),
                ),
            ],
            options={
                "db_table": "payroll_bank_transfers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalaryAdvance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "advance_type",
                    models.CharField(
                        choices=[
                            ("SALARY", "Salary Advance"),
                            ("EMERGENCY", "Emergency Advance"),
                            ("PURCHASE", "Purchase Advance"),
                            ("MEDICAL", "Medical Advance"),
                        ],
                        default="SALARY",
                        max_length=20,
                    ),
                ),
                ("reference_number", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("100.00"))
                        ],
                    ),
                ),
                (
                    "outstanding_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "monthly_deduction",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "installments",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                ("reason", models.TextField()),
                ("purpose_details", models.JSONField(blank=True, default=dict)),
                ("requested_date", models.DateField(auto_now_add=True)),
                ("approved_date", models.DateField(blank=True, null=True)),
                ("disbursement_date", models.DateField(blank=True, null=True)),
                ("completion_date", models.DateField(blank=True, null=True)),
                (
                    "employee_basic_salary",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "max_allowed_percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("50.00"), max_digits=5
                    ),
                ),
                ("advance_count_this_year", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_advances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_advances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_advances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_salary_advances",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["employee", "status"],
                        name="payroll_sal_employe_f8c3d9_idx",
                    ),
                    models.Index(
                        fields=["reference_number"],
                        name="payroll_sal_referen_9c13d8_idx",
                    ),
                    models.Index(
                        fields=["status"], name="payroll_sal_status_15fec0_idx"
                    ),
                    models.Index(
                        fields=["requested_date"], name="payroll_sal_request_0fabef_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PayslipItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("EARNING", "Earning"),
                            ("DEDUCTION", "Deduction"),
                            ("CONTRIBUTION", "Contribution"),
                            ("TAX", "Tax"),
                            ("BONUS", "Bonus"),
                            ("ALLOWANCE", "Allowance"),
                            ("PENALTY", "Penalty"),
                        ],
                        max_length=20,
                    ),
                ),
                ("item_code", models.CharField(max_length=50)),
                ("item_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=8
                    ),
                ),
                ("is_taxable", models.BooleanField(default=True)),
                ("is_epf_applicable", models.BooleanField(default=True)),
                ("is_mandatory", models.BooleanField(default=False)),
                ("calculation_basis", models.CharField(blank=True, max_length=50)),
                ("calculation_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payslip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="payroll.payslip",
                    ),
                ),
            ],
            options={
                "db_table": "payroll_payslip_items",
                "ordering": ["item_type", "item_code"],
                "indexes": [
                    models.Index(
                        fields=["payslip", "item_type"],
                        name="payroll_pay_payslip_d49865_idx",
                    ),
                    models.Index(
                        fields=["item_code"], name="payroll_pay_item_co_427cc5_idx"
                    ),
                    models.Index(
                        fields=["item_type"], name="payroll_pay_item_ty_1aa822_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="payslip",
            index=models.Index(
                fields=["payroll_period", "employee"],
                name="payroll_pay_payroll_f0bc90_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payslip",
            index=models.Index(
                fields=["employee", "status"], name="payroll_pay_employe_fe5dc5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payslip",
            index=models.Index(
                fields=["reference_number"], name="payroll_pay_referen_337b5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payslip",
            index=models.Index(fields=["status"], name="payroll_pay_status_578e15_idx"),
        ),
        migrations.AddIndex(
            model_name="payslip",
            index=models.Index(
                fields=["employee"], name="payroll_pay_employe_778744_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payslip",
            index=models.Index(
                fields=["created_at"], name="payroll_pay_created_929013_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="payslip",
            unique_together={("payroll_period", "employee")},
        ),
        migrations.AddIndex(
            model_name="payrollperiod",
            index=models.Index(
                fields=["year", "month"], name="payroll_per_year_effb6e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payrollperiod",
            index=models.Index(fields=["status"], name="payroll_per_status_1a807a_idx"),
        ),
        migrations.AddIndex(
            model_name="payrollperiod",
            index=models.Index(
                fields=["processing_date"], name="payroll_per_process_f9f4a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payrollperiod",
            index=models.Index(
                fields=["is_active"], name="payroll_per_is_acti_19d671_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="payrollperiod",
            unique_together={("year", "month")},
        ),
        migrations.AddIndex(
            model_name="payrolldepartmentsummary",
            index=models.Index(
                fields=["payroll_period", "department"],
                name="payroll_dep_payroll_4865cd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payrolldepartmentsummary",
            index=models.Index(
                fields=["department"], name="payroll_dep_departm_34007b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="payrolldepartmentsummary",
            unique_together={("payroll_period", "department")},
        ),
        migrations.AddIndex(
            model_name="payrollbanktransfer",
            index=models.Index(
                fields=["payroll_period"], name="payroll_ban_payroll_e89be0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payrollbanktransfer",
            index=models.Index(
                fields=["batch_reference"], name="payroll_ban_batch_r_0a62cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payrollbanktransfer",
            index=models.Index(fields=["status"], name="payroll_ban_status_70ecef_idx"),
        ),
    ]
