# Generated by Django 4.2.16 on 2025-08-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salaryadvance",
            name="purpose_details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
