# Generated by Django 4.2.16 on 2025-09-07 15:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0002_alter_salaryadvance_purpose_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="payslip",
            name="expense_additions",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="payslip",
            name="expense_deductions",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
