# Generated by Django 4.2.16 on 2025-09-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Super Admin"),
                    ("MANAGER", "Manager"),
                    ("CASHIER", "Cashier"),
                    ("SALESMAN", "Salesman"),
                    ("OTHER_STAFF", "Other Staff"),
                    ("CLEANER", "Cleaner"),
                    ("DRIVER", "Driver"),
                    ("ASSISTANT", "Assistant"),
                    ("STOREKEEPER", "Storekeeper"),
                    ("OFFICE_WORKER", "Office Worker"),
                ],
                max_length=50,
            ),
        ),
    ]
