# Generated by Django 4.2.16 on 2025-09-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_importjob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemconfiguration",
            name="setting_type",
            field=models.CharField(
                choices=[
                    ("SYSTEM", "System Setting"),
                    ("SECURITY", "Security Setting"),
                    ("NOTIFICATION", "Notification Setting"),
                    ("ATTENDANCE", "Attendance Setting"),
                    ("PAYROLL", "Payroll Setting"),
                    ("LEAVE", "Leave Setting"),
                    ("DEVICE", "Device Setting"),
                    ("CALCULATION", "Calculation Setting"),
                    ("VALIDATION", "Validation Setting"),
                    ("INTEGRATION", "Integration Setting"),
                    ("TAX", "Tax Setting"),
                    ("ALLOWANCE", "Allowance Setting"),
                    ("BONUS", "Bonus Setting"),
                    ("PENALTY", "Penalty Setting"),
                ],
                default="SYSTEM",
                max_length=20,
            ),
        ),
    ]
