# Generated by Django 4.2.16 on 2025-08-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="contract_number",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
